---
# eedugon: pending to fix users and passwords to monitor multiple clusters
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  namespace: prod
  name: metrics-prod-monitoring-central
spec:
  type: metricbeat
  version: 7.11.2
  elasticsearchRef:
    name: logging-and-metrics
    namespace: monitoring
  #kibanaRef:
  #  name: monitoring
  config:
    http.enabled: true
    http.port: 5066
    http.host: 0.0.0.0
    monitoring.enabled: false
    metricbeat:
      autodiscover:
        providers:
          - type: kubernetes
            scope: cluster
            hints.enabled: false # there's no need to enable hints if we don't have annotations for the metrics
            templates:
              - condition:
                  equals.kubernetes.labels.elasticsearch_k8s_elastic_co/cluster-name: prod-monitoring
                  #equals.kubernetes.labels.stack-monitoring-elastic-co/type: es
                config:
                  - module: elasticsearch
                    metricsets:
                      - ccr
                      - cluster_stats
                      - enrich
                      - index
                      - index_recovery
                      - index_summary
                      - ml_job
                      - node_stats
                      - shard
                    period: 10s
                    hosts: "https://${data.host}:${data.ports.https}"
                    username: ${MONITORED_ES_USERNAME}
                    password: ${MONITORED_ES_PASSWORD}
                    # WARNING: disables TLS as the default certificate is not valid for the pod FQDN
                    # TODO: switch this to "certificate" when available: https://github.com/elastic/beats/issues/8164
                    ssl.verification_mode: "none"
                    xpack.enabled: true
              - condition:
                  equals.kubernetes.labels.kibana_k8s_elastic_co/name: prod-monitoring
                  #equals.kubernetes.labels.stack-monitoring-elastic-co/type: kb
                config:
                  - module: kibana
                    metricsets:
                      - stats
                      - status
                    period: 10s
                    hosts: "https://${data.host}:${data.ports.https}"
                    username: ${MONITORED_ES_USERNAME}
                    password: ${MONITORED_ES_PASSWORD}
                    # WARNING: disables TLS as the default certificate is not valid for the pod FQDN
                    # TODO: switch this to "certificate" when available: https://github.com/elastic/beats/issues/8164
                    ssl.verification_mode: "none"
                    xpack.enabled: true
    processors:
    - add_cloud_metadata: {}
    logging.json: true
  deployment:
    podTemplate:
      metadata:
        labels:
          # allow metricbeat based monitoring of this beat
          mb_collection_enabled: "true"
      spec:
        serviceAccountName: metricbeat
        automountServiceAccountToken: true
        # required to read /etc/beat.yml
        securityContext:
          runAsUser: 0
        containers:
        - name: metricbeat
          ports:
          - containerPort: 5066
            name: monitoring
            protocol: TCP
          env:
          - name: MONITORED_ES_USERNAME
            value: elastic
          - name: MONITORED_ES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: elastic
                name: prod-monitoring-es-elastic-user
