---
# Metricbeat example for ES & Kibana monitoring of a single cluster
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  namespace: dev
  name: metrics-dev-es1-dedicated
spec:
  type: metricbeat
  version: 7.13.3
  elasticsearchRef:
    name: dev-monitoring
  config:
    http.enabled: true
    http.port: 5066
    http.host: 0.0.0.0
    monitoring.enabled: false
    metricbeat:
      autodiscover:
        providers:
          - type: kubernetes
            scope: cluster
            hints.enabled: false # there's no need to enable hints if we don't have annotations for the metrics
            templates:
              - condition:
                  equals.kubernetes.labels.elasticsearch_k8s_elastic_co/cluster-name: dev-es1
                config:
                  - module: elasticsearch
                    metricsets:
                      - ccr
                      - cluster_stats
                      - enrich
                      - index
                      - index_recovery
                      - index_summary
                      - ml_job
                      - node_stats
                      - shard
                    period: 10s
                    hosts: "https://${data.host}:${data.ports.https}"
                    username: "elastic" # to do: use a more restricted user instead
                    password: "${kubernetes.dev.dev-es1-es-elastic-user.elastic}"
                    # mount the CA of the endpoint to monitor to be able to perform certificate verification
                    ssl.verification_mode: "none"
                    xpack.enabled: true
              - condition:
                  equals.kubernetes.labels.kibana_k8s_elastic_co/name: dev-es1
                config:
                  - module: kibana
                    metricsets:
                      - stats
                      - status
                    period: 10s
                    hosts: "https://${data.host}:${data.ports.https}"
                    username: "elastic" # to do: use a more restricted user instead
                    password: "${kubernetes.dev.dev-es1-es-elastic-user.elastic}"
                    # mount the CA of the endpoint to monitor to be able to perform certificate verification
                    ssl.verification_mode: "none"
                    xpack.enabled: true
    processors:
    - add_cloud_metadata: {}
    logging.json: true
  deployment:
    podTemplate:
      metadata:
        labels:
          # allow metricbeat based monitoring of this beat
          mb_collection_enabled: "true"
      spec:
        serviceAccountName: metricbeat
        automountServiceAccountToken: true
        # required to read /etc/beat.yml
        securityContext:
          runAsUser: 0
        containers:
        - name: metricbeat
          ports:
          - containerPort: 5066
            name: monitoring
            protocol: TCP
