apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  namespace: monitoring
  name: logging-and-metrics
spec:
  http:
    service:
      spec:
  #      type: LoadBalancer
        type: ClusterIP
  version: 7.11.2
  nodeSets:
  - name: default50g
    count: 3
    config:
      node.roles: [ master, data, ingest ]
      # For metricbeat based monitoring
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-metricbeat.html
      xpack.monitoring.collection.enabled: true
      xpack.monitoring.elasticsearch.collection.enabled: false
    podTemplate:
      metadata:
        annotations:
          # optional / recommended: disabling self-collecting logs
          co.elastic.logs/enabled: "false"
      spec:
        # tolerations (irrelevant if tains are not configured in k8s nodes)
        tolerations:
          - key: "area"
            operator: "Equal"
            value: "monitoring"
            effect: "NoSchedule"
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms3g -Xmx3g
          resources:
            requests:
              memory: 6Gi
              cpu: 400m
            limits:
              memory: 6Gi
              cpu: 2
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
#        storageClassName: default
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  namespace: monitoring
  name: logging-and-metrics
spec:
  http:
    service:
      #metadata:
      #  annotations:
      #    aaaaa: "aaa"
      spec:
        type: LoadBalancer
  version: 7.11.2
  count: 1
  elasticsearchRef:
    name: logging-and-metrics
  config:
    # For metricbeat based monitoring...
    # https://www.elastic.co/guide/en/kibana/current/monitoring-metricbeat.html
    monitoring.kibana.collection.enabled: false
    # Recommended monitoring setting when ES runs in containers...
    # https://www.elastic.co/guide/en/kibana/current/monitoring-settings-kb.html
    monitoring.ui.container.elasticsearch.enabled: true
  podTemplate:
    metadata:
      annotations:
        #co.elastic.logs/enabled: "true"
        #co.elastic.logs/module: "kibana"
        co.elastic.logs/fileset: "log" # audit fileset will duplicate all logs
    spec:
      # tolerations (irrelevant if tains are not configured in k8s nodes)
      tolerations:
        - key: "area"
          operator: "Equal"
          value: "monitoring"
          effect: "NoSchedule"
      containers:
      - name: kibana
        resources:
          requests:
            memory: 2Gi
            cpu: 500m
          limits:
            memory: 3Gi
            cpu: 1500m
