# review
# not following guidelines from https://raw.githubusercontent.com/elastic/beats/master/deploy/kubernetes/filebeat-kubernetes.yaml
# missing data path volume
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: logs-k8s
  namespace: monitoring
spec:
  type: filebeat
  version: 7.11.2
  elasticsearchRef:
    name: logging-and-metrics
  kibanaRef:
    name: logging-and-metrics
  config:
    # Disabled mb based monitoring and enabled internal collection instead because of hostNetwork
    # http.enabled: true
    # http.port: 5067
    # http.host: 0.0.0.0
    monitoring.enabled: true
    filebeat:
      autodiscover:
        providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints:
            enabled: true
            default_config:
              type: container
              paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log
    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
    monitoring.enabled: false
  daemonSet:
    podTemplate:
      metadata:
        labels:
          # NOT allow metricbeat based monitoring of this beat
          mb_collection_enabled: "false"
        annotations:
          # disabling self-collecing logs
          co.elastic.logs/enabled: "false"
      spec:
        # Toleration for all type of hints (we want FB to run in all nodes)
        tolerations:
          - effect: NoExecute
            operator: Exists
          - effect: NoSchedule
            operator: Exists
          - key: CriticalAddonsOnly
            operator: Exists
        serviceAccountName: filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        containers:
        - name: filebeat
          ports:
          - containerPort: 5067
            name: monitoring
            protocol: TCP
          securityContext:
            runAsUser: 0 # needed for hostPath data volume and /etc/beat.yml mount by ECK
            # If using Red Hat OpenShift uncomment this:
            #privileged: true
          volumeMounts:
          - name: data
            mountPath: /usr/share/filebeat/data
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        # data folder stores a registry of read status for all files, so we don't send everything again on a Filebeat pod restart
        - name: data
          hostPath:
            # When filebeat runs as non-root user, this directory needs to be writable by group (g+w).
            path: /var/lib/filebeat-data-logs-k8s
            type: DirectoryOrCreate
